# Dependabot version updates configuration
# Docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Rust (Cargo)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Node.js (npm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"